name: si_atma
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  build_runner: ^2.1.11
  calendar_timeline: ^1.0.4
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  datetime_picker_formfield: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^9.7.0
  freezed: ^2.0.4
  freezed_annotation: ^2.0.3
  google_fonts: ^3.0.1
  intl: ^0.17.0
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  sqflite: ^2.0.2
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
